# Указывает версию синтаксиса, чтобы Docker понимал правила чтения файла
version: '3.8'

services:
  
  # Сервис бэкенда (наше Node.js API)
  backend:
    # Говорит Докеру собрать образ самостоятельно из исходного кода
    build: 
      context: ./server         # Папка, где лежит исходный код
      dockerfile: Dockerfile    # Файл-чертеж для сборки
      
    # Красивое имя контейнера для удобного просмотра в терминале
    container_name: codeschool_backend
    
    # Политика перезапуска: Докер автоматически поднимет сервер при падении или перезагрузке Ubuntu
    restart: always
    
    # Проброс портов: ЛЕВЫЙ (интернет) связывается с ПРАВЫМ (внутри контейнера)
    ports:
      - "3000:3000"
      
    # Тома (Volumes): создают постоянные "туннели" к жесткому диску хоста (Ubuntu).
    # Гарантируют, что данные не исчезнут при удалении или перезапуске контейнера!
    volumes:
      - ./server/dev.db:/usr/src/app/dev.db                        # Сохранение базы данных SQLite
      - ./server/public/uploads:/usr/src/app/public/uploads        # Сохранение загруженных файлов/картинок
      
    # Подключаем секреты (например, JWT_SECRET) внутрь контейнера
    env_file:
      - ./server/.env
      
  # Сервис фронтенда (наше Next.js приложение)
  frontend:
    build: 
      context: ./client
      dockerfile: Dockerfile
      # Передача аргументов (args) внутрь процесса сборки (npm run build).
      # Необходимо, чтобы Next.js намертво "запек" этот IP-адрес в свой код для связи с бэкендом.
      args:
        - NEXT_PUBLIC_API_URL=http://93.183.83.231:3000/api
        
    container_name: codeschool_frontend
    restart: always
    
    # Связываем порт 3001 в интернете с портом 3001 внутри контейнера фронтенда
    ports:
      - "3001:3001"
      
    # Задает порядок запуска: фронтенд включится только после старта бэкенда
    depends_on:
      - backend